# Generated by Django 3.1.5 on 2021-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210125_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('moderation', 'Moderation'), ('published', 'Published'), ('rejected', 'Rejected')], default='moderation', max_length=10),
        ),
    ]
