# Generated by Django 3.1.5 on 2021-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(default=None),
        ),
    ]
